version: '3.8'

services:
  power-consumption-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: household-power-api
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - FLASK_DEBUG=False
      - FLASK_ENV=production
    restart: unless-stopped
    networks:
      - power-consumption-net

networks:
  power-consumption-net:
    driver: bridge
